### PR TITLE
Added possibility to suppress or throw exceptions during config loading

### PR DESCRIPTION
**Pull request by peterdeme**
Hi Guys,

So we are getting serious troubles becauses of this.. Actually I don't really understand why is it good to suppress config loading error, but its fine I made it true by default.

Thanks
Peter

### CODE REVIEW

**Comment by adamhathcock** [comment]
The suppression of errors was in the original python: https://github.com/fugue/credstash/blob/master/credstash.py#L343
I recall there were valid errors because of dynamo querying and ignoring was safe because the value just wouldn't be in the list.

I'm not sure what issues you're seeing.

Also, if you were going to do this, you should put the option on the options class provided.

**Comment by peterdeme** [comment]
"I'm not sure what issues you're seeing."

Well, lacking permission of reading from table, decrypting with key etc.
The original code is bad as well, valid errors must be **allowed explicitly**, but this implementation suppresses literally every error which is dangerous.

"Also, if you were going to do this, you should put the option on the options class provided."

Okay.

**Comment by peterdeme** [comment]
Is this fine by you in the current state @adamhathcock ?

**Comment by adamhathcock** [comment]
Sorry.  I forgot about this.

Do you mind bumping the minor version like this?: https://github.com/Narochno/Narochno.Credstash/pull/14/files

**Comment by peterdeme** [comment]
Sure, bumped minor to 2.2.0

**Review by adamhathcock — APPROVED** [review]

**Pull request merged**
