### PR TITLE
Extend credstash - Added 'GetAllAsync' and 'PutAsync' methods to credstash class

### PR DESCRIPTION
**Pull request by germrfy**
* Added new methods to ICredstash interface
* Added an optional 'expires' to dynamodb credstash items for use in 'TTL' scenarios

### CODE REVIEW

**Comment by dh-ger** [comment]
Hi,

I needed to implement the 'GetAll' and 'Put' methods from the original credstash library for a project I am working on.
I also added the ability to optionally specify an 'expires' time when writing secrets to DynamoDB using credstash.

Thanks,

Ger

**Comment by germrfy** [comment]
Hi,

I needed to implement the 'Put' and 'GetAll' methods from the original credstash library for a project I am working on.

I also added the ability to optionally specify an 'expires' time when writing secrets to DynamoDB which is useful if you want to add a TTL to the table.

Thanks,

Ger

**Comment by adamhathcock** [comment]
Do you mind incrementing the minor version of the library?

**Comment by germrfy** [comment]
No problem, bumped the version to 2.3.0

**Review by adamhathcock — APPROVED** [review]

**Pull request merged**
